---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-uat
  labels:
    app: api-gw-uat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gw-uat
  template:
    metadata:
      labels:
        app: api-gw-uat
    spec:
      containers:
      - name: nginx
        image: quay.io/brandon_tsai/testlab:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-gw-uat
spec:
  selector:
    app: api-gw-uat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
