apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  labels:
    app: caddy
spec:
  selector:
    matchLabels:
      app: caddy
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/role: 'internal-app'
        vault.hashicorp.com/agent-inject-secret-database-config.txt: 'internal/data/database/config'
        vault.hashicorp.com/agent-inject-template-database-config.txt: |
          {{- with secret "internal/data/database/config" -}}
          export DB="postgresql://{{ .Data.data.username }}:{{ .Data.data.password }}@postgres:5432/wizard"
          {{- end -}}
      labels:
        app: caddy
    spec:
      serviceAccountName: internal-app
      containers:
        - name: caddy
          image: caddy:2.4.1